---
# Source: flux/templates/kube.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-kube-config
  namespace: flux
data:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: default
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []
